env:
  es6: true
  browser: true
  commonjs: true
  jest: true

rules:
  no-console: 'error'
  semi: 'error'
  no-undef: 'warn'

extends:
  [
    'eslint:recommended',
    'plugin:react/recommended',
    'plugin:jsx-a11y/recommended',
  ]

parser: 'babel-eslint'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react']

settings:
  react:
    version: 'detect'
