env:
  es6: true
  browser: true
  commonjs: true
  jest: true

rules:
  no-console: 'warn'
  semi: 'error'
  no-undef: 'warn'

extends: ['eslint:recommended', 'plugin:react/recommended']

# parser: 'babel/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

plugins: ['react']

settings:
  react:
    version: 'detect'
